#!/bin/bash

swiftformat="Pods/SwiftFormat/CommandLineTool/swiftformat"

if [ ! -f $swiftformat ]; then
  echo "Swiftformat is not installed in ${swiftformat} directory"
  exit 0
fi

git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).swift$' | while read line; do
  "Pods/SwiftFormat/CommandLineTool/swiftformat" "${line}"
  git add "$line"
done
